version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: event-booking-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network

volumes:
  jenkins_data:

networks:
  jenkins-network:
    driver: bridge
