apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: event-booking-system
  labels:
    app: event-booking-app
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # DATABASE_URL: mysql://user:userpassword@mysql-service:3306/eventbooking
  database-url: bXlzcWw6Ly91c2VyOnVzZXJwYXNzd29yZEBteXNxbC1zZXJ2aWNlOjMzMDYvZXZlbnRib29raW5n
  # AUTH_SECRET: your-auth-secret-key-here
  auth-secret: eW91ci1hdXRoLXNlY3JldC1rZXktaGVyZQ==
  # MYSQL_ROOT_PASSWORD: rootpassword
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # MYSQL_PASSWORD: userpassword  
  mysql-password: dXNlcnBhc3N3b3Jk
