apiVersion: v2
name: event-booking-chart
description: A Helm chart for Event Booking System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - event-booking
  - nodejs
  - nextjs
  - mysql
home: https://github.com/yourusername/event-booking-system
sources:
  - https://github.com/yourusername/event-booking-system
maintainers:
  - name: Your Name
    email: your.email@example.com
